# Generated by Django 5.1.4 on 2026-07-09 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Public handle; may be used to log in instead of email.', max_length=150, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('facebook', 'Facebook')], db_index=True, max_length=20)),
                ('uid', models.CharField(help_text="Provider's stable user id.", max_length=255)),
                ('extra_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
                'constraints': [models.UniqueConstraint(fields=('provider', 'uid'), name='unique_provider_uid')],
            },
        ),
    ]
