"""Tests for the projects model and API."""

from __future__ import annotations

import pytest

from apps.projects.models import Project, ProjectCategory

pytestmark = pytest.mark.django_db


def _make(title="Demo", **kw):
    defaults = dict(summary="s", category=ProjectCategory.WEB, published=True)
    defaults.update(kw)
    return Project.objects.create(title=title, **defaults)


class TestProjectModel:
    def test_slug_autogenerated(self):
        p = _make(title="My Cool Project")
        assert p.slug == "my-cool-project"

    def test_timestamps(self):
        p = _make()
        assert p.created_at and p.updated_at


class TestProjectAPI:
    def test_public_lists_only_published(self, api):
        _make(title="Live", published=True)
        _make(title="Draft", published=False)
        resp = api.get("/api/projects/")
        assert resp.status_code == 200
        titles = [p["title"] for p in resp.data["results"]]
        assert "Live" in titles and "Draft" not in titles

    def test_filter_by_category(self, api):
        _make(title="Web1", category=ProjectCategory.WEB)
        _make(title="Mob1", category=ProjectCategory.MOBILE)
        resp = api.get("/api/projects/?category=mobile")
        assert [p["title"] for p in resp.data["results"]] == ["Mob1"]

    def test_filter_featured(self, api):
        _make(title="Feat", is_featured=True)
        _make(title="Plain", is_featured=False)
        resp = api.get("/api/projects/?featured=true")
        assert [p["title"] for p in resp.data["results"]] == ["Feat"]

    def test_search(self, api):
        _make(title="Unicorn Platform")
        _make(title="Other")
        resp = api.get("/api/projects/?search=unicorn")
        assert [p["title"] for p in resp.data["results"]] == ["Unicorn Platform"]

    def test_write_requires_admin(self, api):
        resp = api.post("/api/projects/", {"title": "X", "summary": "y"}, format="json")
        assert resp.status_code in (401, 403)

    def test_admin_can_create(self, auth_admin):
        resp = auth_admin.post(
            "/api/projects/",
            {"title": "Created", "summary": "via api", "category": "web"},
            format="json",
        )
        assert resp.status_code == 201
        assert resp.data["slug"] == "created"

    def test_admin_sees_unpublished(self, auth_admin):
        _make(title="Hidden", published=False)
        resp = auth_admin.get("/api/projects/")
        assert "Hidden" in [p["title"] for p in resp.data["results"]]
